# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1C7sMAxvB8lJxg7R2K5zQh4X2OzWlHiZs
"""

pip install openai

import subprocess

# Install OpenAI 
subprocess.check_call(['pip', 'install', 'openai'])

import openai

openai.api_key = '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'

# Define a function to generate a response from the language model
def generate_response(prompt):
    response = openai.Completion.create(
        engine='text-davinci-003',  # Specify the OpenAI language model
        prompt=prompt,
        max_tokens=50,  # Control the length of the response
        n=1,  # Number of responses to generate
        stop=None,  # Stop generating after a certain string
        temperature=0.7,  # Control the randomness of the response
        frequency_penalty=0.0,
        presence_penalty=0.0
    )
    return response.choices[0].text.strip()

# Process and analyze the dataset
def calculate_total_expenses(dataset):
    total_expenses = sum(transaction['amount'] for transaction in dataset if transaction['category'] != 'income')
    return total_expenses

# Dataset 
dataset = [
    {"date": "2021-01-01", "amount": 1000, "category": "income", "description": "salary"},
    {"date": "2021-01-02", "amount": -50, "category": "groceries", "description": "milk and eggs"},
    {"date": "2021-01-03", "amount": -100, "category": "entertainment", "description": "movie tickets"},
    {"date": "2021-01-04", "amount": -20, "category": "transportation", "description": "bus fare"},
    {"date": "2021-01-05", "amount": -200, "category": "bills", "description": "electricity bill"},
    {"date": "2021-01-06", "amount": -30, "category": "groceries", "description": "bread and cheese"},
    {"date": "2021-01-07", "amount": -150, "category": "clothing", "description": "new shoes"},
    {"date": "2021-01-08", "amount": -40, "category": "healthcare", "description": "prescription drugs"},
    {"date": "2021-01-09", "amount": -80, "category": "education", "description": "online course"},
    {"date": "2021-01-10", "amount": -60, "category": "entertainment", "description": "pizza delivery"},
    {"date": "2021-01-11", "amount": -25, "category": "transportation", "description": "taxi ride"},
    {"date": "2021-01-12", "amount": -300, "category": "bills", "description": "internet bill"},
    {"date": "2021-01-13", "amount": -50, "category": "groceries", "description": "fruits and vegetables"}
]

# Sample query
user_query = "What are my total expenses for the month of April?"

response = generate_response(user_query)

# Calculate the total expenses for the month of April
total_expenses = calculate_total_expenses
total_expenses = calculate_total_expenses(dataset)

# Print the generated 
print("Response:", response)
print("Total Expenses:", total_expenses)